spring:
  lifecycle:
    timeout-per-shutdown-phase: 5m

server:
  forward-headers-strategy: native
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 30
    max-connections: 700
    accept-count: 300
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
