spring:
  application:
    name: zzol
  config:
    import:
      - "classpath:config/database.yml"
      - "classpath:config/redis.yml"
      - "classpath:config/security.yml"
      - "classpath:config/game.yml"
      - "classpath:config/service.yml"
      - "classpath:config/websocket.yml"
      - "classpath:config/resilience4j.yml"
      - "classpath:config/monitoring.yml"
      - "classpath:config/server.yml"
      - "classpath:config/storage.yml"
      - "classpath:config/zzolbot.yml"
