export const ANIMATION_DURATION = {
  RIPPLE: 100,
  BACKGROUND_PRESS: 100,
  SCALE_PRESS: 100,
  DASHBOARD_DISPLAY: 5500,
  DASHBOARD_FADE: 400,
};

export const ANIMATION_SCALE = {
  SCALE_PRESS: 0.98,
};
