export const RACING_Z_INDEX = {
  LINE: 1,
  PROGRESS_BAR: 1,
  PROGRESS_BAR_ME: 2,
  PROGRESS_MARKER: 2,
  PROGRESS_MARKER_ME: 3,
  PLAYER: 10,
  RANK: 200,
  OVERLAY: 900,
  GOAL: 1000,
  FINISH: 1000,
} as const;
