spring:
  application:
    name: zzol
  config:
    import:
      - "config/database.yml"
      - "config/redis.yml"
      - "config/security.yml"
      - "config/game.yml"
      - "config/service.yml"
      - "config/websocket.yml"
      - "config/resilience4j.yml"
      - "config/monitoring.yml"
      - "config/server.yml"
      - "config/storage.yml"
      - "config/zzolbot.yml"
